local M = {}

local message = 'Generated by invero.nvim. Run ./scripts/build to regenerate.'

local function prefixed(prefix)
  return function(content)
    return prefix .. ' ' .. message .. '\n' .. content
  end
end

local passthrough = function(content)
  return content
end

local formatters = {
  conf = prefixed('#'),
  kdl = prefixed('//'),
  toml = prefixed('#'),
}

function M.add(content, filetype)
  return (formatters[filetype] or passthrough)(content)
end

return M
