[colors]
background = "#eeeeee"
foreground = "#444444"
cursor_bg = "#005fff"
cursor_border = "#9e9e9e"
cursor_fg = "#eeeeee"
selection_bg = "#dadada"
selection_fg = "#444444"
split = "#005fff"
compose_cursor = "#d75f00"
scrollbar_thumb = "#9e9e9e"

copy_mode_active_highlight_bg = "#dadada"
copy_mode_active_highlight_fg = "#d75f00"
copy_mode_inactive_highlight_bg = "#eeeeee"
copy_mode_inactive_highlight_fg = "#d75f00"

ansi = ["#444444", "#ff0000", "#00af5f", "#d75f00", "#005fff", "#5f5f87", "#afd7ff", "#eeeeee"]
brights = ["#444444", "#ff0000", "#00af5f", "#d75f00", "#005fff", "#5f5f87", "#afd7ff", "#eeeeee"]

[colors.tab_bar]
inactive_tab_edge = "#ff0000"
background = "#444444"

[colors.tab_bar.active_tab]
fg_color = "#eeeeee"
bg_color = "#444444"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#9e9e9e"
bg_color = "#444444"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#dadada"
bg_color = "#444444"
